services:
  jvb:
    image: docker.io/jitsi/jvb:jvb-2.3-291-gb4b5ccc8c-1
    restart: ${RESTART_POLICY}
    ports:
      - "10000:10000/udp"
    volumes:
      - ${CONFIG}/jvb:/config
    environment:
      - JVB_AUTH_USER=${JVB_AUTH_USER}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - JVB_HOST=jvb
      - JVB_BREWERY_MUC_JVB_BREAKAUTH_VISITOR=
      - JVB_OCTO_REGION=region1
      - JVB_STUN_SERVERS=${JVB_STUN_SERVERS}
      - PUBLIC_URL=${PUBLIC_URL}
      - XMPP_SERVER=prosody
      - XMPP_DOMAIN=${JITSI_DOMAIN}
      - XMPP_AUTH_DOMAIN=auth.${JITSI_DOMAIN}
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.${JITSI_DOMAIN}
      - TZ=${TZ}
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    networks:
      - jitsinet

  web:
    image: docker.io/jitsi/web:web-1.0.9207-1
    restart: ${RESTART_POLICY}
    ports:
      - "18080:80"
      - "18443:443"
    volumes:
      - ${CONFIG}/jitsi-meet:/config
      - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts
    environment:
      - PUBLIC_URL=${PUBLIC_URL}
      - XMPP_DOMAIN=${JITSI_DOMAIN}
      - XMPP_GUEST_DOMAIN=guest.${JITSI_DOMAIN}
      - XMPP_BOSH_URL_BASE=http://prosody:5280
      - JICOFO_AUTH_USER=${JICOFO_AUTH_USER}
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JVB_AUTH_USER=${JVB_AUTH_USER}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - JVB_HOST=jvb
      - JICOFO_HOST=jicofo
      - ENABLE_AUTH=${ENABLE_AUTH}
      - ENABLE_GUESTS=${ENABLE_GUESTS}
      - ENABLE_LETSENCRYPT=0
      - DISABLE_HTTPS=1
      - JWT_APP_SECRET=${JWT_APP_SECRET}
      - TZ=${TZ}
    depends_on:
      - jvb
      - prosody
    networks:
      - jitsinet

  jicofo:
    image: docker.io/jitsi/jicofo:unstable
    restart: ${RESTART_POLICY}
    volumes:
      - ${CONFIG}/jicofo:/config
    environment:
      - PUBLIC_URL=${PUBLIC_URL}
      - XMPP_SERVER=prosody
      - XMPP_DOMAIN=${JITSI_DOMAIN}
      - XMPP_AUTH_DOMAIN=auth.${JITSI_DOMAIN}
      - XMPP_MUC_DOMAIN=muc.${JITSI_DOMAIN}
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.${JITSI_DOMAIN}
      - JICOFO_AUTH_USER=${JICOFO_AUTH_USER}
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JVB_AUTH_USER=${JVB_AUTH_USER}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - JVB_HOST=jvb
      - JICOFO_CONF_SECRET=${JICOFO_CONF_SECRET}
      - ENABLE_SIP=0
      - ENABLE_AUTH=${ENABLE_AUTH}
      - TZ=${TZ}
    depends_on:
      - jvb
      - prosody
    networks:
      - jitsinet

  prosody:
    image: docker.io/jitsi/prosody:unstable
    restart: ${RESTART_POLICY}
    volumes:
      - ${CONFIG}/prosody/config:/config
      - ${CONFIG}/prosody/plugins:/prosody-plugins-custom:ro
    environment:
      - PUBLIC_URL=${PUBLIC_URL}
      - XMPP_DOMAIN=${JITSI_DOMAIN}
      - XMPP_GUEST_DOMAIN=guest.${JITSI_DOMAIN}
      - XMPP_AUTH_DOMAIN=auth.${JITSI_DOMAIN}
      - XMPP_MUC_DOMAIN=muc.${JITSI_DOMAIN}
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.${JITSI_DOMAIN}
      - JITSI_DOMAIN=${JITSI_DOMAIN}
      - ENABLE_AUTH=${ENABLE_AUTH}
      - ENABLE_GUESTS=${ENABLE_GUESTS}
      - AUTH_TYPE=${AUTH_TYPE}
      - PROSODY_AUTH_TYPE=jwt
      - JWT_AUTH_TYPE=token
      - JWT_APP_SECRET=${JWT_APP_SECRET}
      - JWT_APP_ID=iqra-app
      - JICOFO_AUTH_USER=${JICOFO_AUTH_USER}
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JVB_AUTH_USER=${JVB_AUTH_USER}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - TZ=${TZ}
    networks:
      - jitsinet

networks:
  jitsinet:
    name: jitsi-net
